=== fred-oo/jSmaTeP/jsmatep-composer-xsd/src/main/resources/xsd/jSmaTeP-Composer-Config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://jsmatep.kardass.com/schema/jSmaTeP-Composer-Config"
    xmlns:tns="http://jsmatep.kardass.com/schema/jSmaTeP-Composer-Config"
    elementFormDefault="qualified">
    <xsd:simpleType name="supported-field-type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="BigDecimal"/>
            <xsd:enumeration value="char"/>
            <xsd:enumeration value="Character"/>
            <xsd:enumeration value="Date"/>
            <xsd:enumeration value="Decimal"/>
            <xsd:enumeration value="double"/>
            <xsd:enumeration value="Double"/>
            <xsd:enumeration value="float"/>
            <xsd:enumeration value="Float"/>
            <xsd:enumeration value="int"/>
            <xsd:enumeration value="Integer"/>
            <xsd:enumeration value="long"/>
            <xsd:enumeration value="Long"/>
            <xsd:enumeration value="string"/>
            <xsd:enumeration value="String"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="field-type">
        <xsd:sequence/>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="position" type="xsd:int" use="required"/>
        <xsd:attribute name="length" type="xsd:int" use="optional"/>
        <xsd:attribute name="type" type="tns:supported-field-type" use="required"/>
        <xsd:attribute name="format" type="xsd:string" use="optional"/>
        <xsd:attribute name="show-decimal-separator" type="xsd:boolean" use="optional" default="true"/>
        <xsd:attribute name="fill-left" type="xsd:string" use="optional"/>
        <xsd:attribute name="fill-right" type="xsd:string" use="optional"/>
    </xsd:complexType>
    <xsd:complexType name="fixed-length-type">
        <xsd:attribute name="record-length" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="csv-type">
        <xsd:attribute name="delimiter" type="xsd:string" use="required"/>
        <xsd:attribute name="field-count" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:complexType name="record-composer-config-type">
        <xsd:sequence>
            <xsd:element name="type" nillable="false">
                <xsd:complexType>
                    <xsd:choice minOccurs="1" maxOccurs="1">
                        <xsd:element name="fixed-length" type="tns:fixed-length-type"/>
                        <xsd:element name="csv" type="tns:csv-type"/>
                    </xsd:choice>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="value-object" type="xsd:string" nillable="false"></xsd:element>
            <!-- xsd:element name="record-length" type="xsd:int" nillable="false"></xsd:element -->
            <xsd:element name="fields" nillable="false">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="field" type="tns:field-type" maxOccurs="unbounded"></xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="version" type="xsd:string" use="optional" default="0.1"/>
    </xsd:complexType>
    <xsd:element name="jSmaTeP-Composer-Config" type="tns:record-composer-config-type"></xsd:element>
</xsd:schema>

=== fred-oo/jSmaTeP/jsmatep-codegenerator/src/test/resources/com/kardass/jsmatep/codegenerator/Export-FixedLength-Config.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : jSmaTeP-Export-Config.xml
    Created on : 19. August 2009, 21:47
    Author     : Manfred Kardass
    Description:
        Purpose of the document follows.
-->

<ns0:jSmaTeP-Composer-Config  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://jsmatep.kardass.com/schema/jSmaTeP-Composer-Config'
   xsi:schemaLocation='http://jsmatep.kardass.com/schema/jSmaTeP-Composer-Config jSmaTeP-Composer-Config.xsd' version="0.1">
    <ns0:type>
        <ns0:fixed-length record-length="55"></ns0:fixed-length>
    </ns0:type>
    <ns0:value-object>de.kardass.jsmatep.out.ExporterTestValueObject</ns0:value-object>
    <ns0:fields>
        <ns0:field name="a" position="0" length="2" type="String"></ns0:field>
        <ns0:field name="b" position="2" length="8" type="Date" format="yyyyMMdd"></ns0:field>
        <ns0:field name="c" position="10" length="3" type="Integer"></ns0:field>
        <ns0:field name="d" position="13" length="5" type="float"></ns0:field>
        <ns0:field name="e" position="18" length="5" type="Decimal"></ns0:field>
        <ns0:field name="f" position="23" length="1" type="String"></ns0:field>
        <ns0:field name="g" position="24" length="5" type="Decimal" format="0.00" show-decimal-separator="false"></ns0:field>
        <ns0:field name="h" position="29" length="6" type="Decimal" format="0.00" show-decimal-separator="true"></ns0:field>
        <ns0:field name="i" position="35" length="10" type="Decimal" format="0.00" show-decimal-separator="false" fill-left=" "></ns0:field>
        <ns0:field name="j" position="45" length="10" type="Decimal" format="0.00" show-decimal-separator="true" fill-right="-"></ns0:field>
    </ns0:fields>

</ns0:jSmaTeP-Composer-Config>
