=== fred-oo/jSmaTeP/jsmatep-parser-xsd/src/main/resources/xsd/jSmaTeP-Parser-Config.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://jsmatep.kardass.com/schema/jSmaTeP-Parser-Config"
    xmlns:tns="http://jsmatep.kardass.com/schema/jSmaTeP-Parser-Config"
    elementFormDefault="qualified">
    <xsd:simpleType name="supported-field-type">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="BigDecimal"/>
            <xsd:enumeration value="char"/>
            <xsd:enumeration value="Character"/>
            <xsd:enumeration value="Date"/>
            <xsd:enumeration value="Decimal"/>
            <xsd:enumeration value="double"/>
            <xsd:enumeration value="Double"/>
            <xsd:enumeration value="float"/>
            <xsd:enumeration value="Float"/>
            <xsd:enumeration value="int"/>
            <xsd:enumeration value="Integer"/>
            <xsd:enumeration value="long"/>
            <xsd:enumeration value="Long"/>
            <xsd:enumeration value="string"/>
            <xsd:enumeration value="String"/>
        </xsd:restriction>
    </xsd:simpleType>
    <xsd:complexType name="field-type">
        <xsd:sequence/>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="bean-property-name" type="xsd:string" use="optional"/>
        <xsd:attribute name="position" type="xsd:int" use="required"/>
        <xsd:attribute name="length" type="xsd:int" use="required"/>
        <xsd:attribute name="type" type="tns:supported-field-type" use="required"/>
        <xsd:attribute name="format" type="xsd:string" use="optional"/>
        <xsd:attribute name="null-value" type="xsd:string" use="optional"/>
        <xsd:attribute name="default-value" type="xsd:string" use="optional"/>
    </xsd:complexType>
    <xsd:complexType name="variable-length-type">
        <xsd:attribute name="min-record-length" type="xsd:integer" use="optional" />
        <xsd:attribute name="max-record-length" type="xsd:integer" use="optional" />
        <xsd:attribute name="fill-with" type="xsd:string" use="optional" default=""/>
    </xsd:complexType>
    <xsd:complexType name="fixed-length-type">
        <xsd:attribute name="record-length" type="xsd:int" use="required" />
        <xsd:attribute name="fill-with" type="xsd:string" use="optional" default=""/>
    </xsd:complexType>
    <xsd:complexType name="csv-type">
        <xsd:attribute name="delimiter" type="xsd:string" use="required" />
        <xsd:attribute name="field-count" type="xsd:int" use="required" />
    </xsd:complexType>
    <xsd:complexType name="record-parser-config-type">
        <xsd:sequence>
            <xsd:element name="type" nillable="false">
                <xsd:complexType>
                    <xsd:choice minOccurs="1" maxOccurs="1">
                        <xsd:element name="variable-length" type="tns:variable-length-type"/>
                        <xsd:element name="fixed-length" type="tns:fixed-length-type"/>
                        <xsd:element name="csv" type="tns:csv-type"/>
                    </xsd:choice>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="value-object" type="xsd:string" nillable="false"></xsd:element>
            <xsd:element name="continue-on-record-error" type="xsd:boolean" default="false" nillable="false" minOccurs="0"/>
            <xsd:element name="skip-record" nillable="true">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="starts-with" type="xsd:string" maxOccurs="unbounded" nillable="false" minOccurs="0"></xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="fields" nillable="false">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="field" type="tns:field-type" maxOccurs="unbounded"></xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="version" type="xsd:string" use="optional"/>
    </xsd:complexType>
    <xsd:element name="jSmaTeP-Parser-Config" type="tns:record-parser-config-type"></xsd:element>
</xsd:schema>

=== fred-oo/jSmaTeP/jsmatep-parser/src/test/resources/com/kardass/jsmatep/parser/VariableLengthFileParserTest.xml
<?xml version="1.0" encoding="UTF-8"?>

<ns0:jSmaTeP-Parser-Config  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://jsmatep.kardass.com/schema/jSmaTeP-Parser-Config'
   xsi:schemaLocation='http://jsmatep.kardass.com/schema/jSmaTeP-Parser-Config jSmaTeP-Parser-Config.xsd' version="1.1.0">

    <ns0:type>
        <ns0:variable-length max-record-length="29"></ns0:variable-length>
    </ns0:type>
    <ns0:value-object>com.kardass.jsmatep.parser.ImporterTestValueObject</ns0:value-object>
    <ns0:fields>
        <ns0:field name="a" bean-property-name="someOtherName" position="0" length="2" type="String"></ns0:field>
        <ns0:field name="aaa" position="0" length="10" type="String"></ns0:field>
        <ns0:field name="b" position="2" length="8" type="Date" format="yyyyMMdd"></ns0:field>
        <ns0:field name="c" position="10" length="3" type="Integer"></ns0:field>
        <ns0:field name="d" position="13" length="5" type="float"></ns0:field>
        <ns0:field name="e" position="18" length="5" type="Decimal"></ns0:field>
        <ns0:field name="f" position="23" length="1" type="String"></ns0:field>
        <ns0:field name="g" position="24" length="5" type="Decimal" format="3,2"></ns0:field>
    </ns0:fields>
</ns0:jSmaTeP-Parser-Config>

=== fred-oo/jSmaTeP/jsmatep-parser/src/test/resources/com/kardass/jsmatep/parser/setterlogic/Setter-Logic-Test-Config.xml
<?xml version="1.0" encoding="UTF-8"?>

<ns0:jSmaTeP-Parser-Config  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://jsmatep.kardass.com/schema/jSmaTeP-Parser-Config'
   xsi:schemaLocation='http://jsmatep.kardass.com/schema/jSmaTeP-Parser-Config jSmaTeP-Parser-Config.xsd' 
   version="1.0.0">

    <ns0:type>
        <ns0:variable-length max-record-length="14"></ns0:variable-length>
    </ns0:type>
    <ns0:value-object>com.kardass.jsmatep.parser.setterlogic.SetterLogicTestValueObject</ns0:value-object>
    <ns0:fields>
        <ns0:field name="a" position="0" length="2" type="String"></ns0:field>
        <ns0:field name="b" position="2" length="8" type="Date" format="yyyyMMdd" null-value="00000000" default-value="99991231"></ns0:field>
        <ns0:field name="c" position="10" length="4" type="Integer" default-value="9999"></ns0:field>
    </ns0:fields>
</ns0:jSmaTeP-Parser-Config>

=== fred-oo/jSmaTeP/jsmatep-parser/src/test/resources/com/kardass/jsmatep/parser/adjust/Adjust-Config.xml
<?xml version="1.0" encoding="UTF-8"?>

<ns0:jSmaTeP-Parser-Config  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://jsmatep.kardass.com/schema/jSmaTeP-Parser-Config'
   xsi:schemaLocation='http://jsmatep.kardass.com/schema/jSmaTeP-Parser-Config jSmaTeP-Parser-Config.xsd' 
   version="1.0.0">

    <ns0:type>
        <ns0:fixed-length record-length="16" fill-with=" "></ns0:fixed-length>
    </ns0:type>
    <ns0:value-object>com.kardass.jsmatep.parser.adjust.AdjustTestValueObject</ns0:value-object>
    <!--  ns0:continue-on-record-error>false</ns0:continue-on-record-error -->
    <ns0:fields>
        <ns0:field name="a" position="0" length="2" type="String"></ns0:field>
        <ns0:field name="b" position="2" length="2" type="String"></ns0:field>
        <ns0:field name="c" position="4" length="8" type="Date" format="yyyyMMdd"></ns0:field>
        <ns0:field name="d" position="12" length="4" type="Integer"></ns0:field>
    </ns0:fields>
</ns0:jSmaTeP-Parser-Config>

=== fred-oo/jSmaTeP/jsmatep-parser/src/test/resources/com/kardass/jsmatep/parser/CsvFileParserTest.xml
<?xml version="1.0" encoding="UTF-8"?>

<ns0:jSmaTeP-Parser-Config  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://jsmatep.kardass.com/schema/jSmaTeP-Parser-Config'
   xsi:schemaLocation='http://jsmatep.kardass.com/schema/jSmaTeP-Parser-Config jSmaTeP-Parser-Config.xsd' version="">

    <ns0:type>
        <ns0:csv delimiter=";" field-count="7"/>
    </ns0:type>
    <ns0:value-object>com.kardass.jsmatep.parser.ImporterTestValueObject</ns0:value-object>
    <ns0:skip-record>
        <ns0:starts-with>#</ns0:starts-with>
    </ns0:skip-record>
    <ns0:fields>
        <ns0:field name="a" bean-property-name="someOtherName" position="0" type="String"></ns0:field>
        <ns0:field name="b" position="1" type="Date" format="yyyyMMdd"></ns0:field>
        <ns0:field name="c" position="2" type="Integer"></ns0:field>
        <ns0:field name="d" position="3" type="float"></ns0:field>
        <ns0:field name="e" position="4" type="Decimal"></ns0:field>
        <ns0:field name="f" position="5" type="String"></ns0:field>
        <ns0:field name="g" position="6" type="Decimal" format="3,2"></ns0:field>
<!--
        <ns0:field name="f" position="5" max-length="1" type="String"></ns0:field>
        <ns0:field name="g" position="6" min-length="2" max-length="6" type="Decimal" format="3,2"></ns0:field>
-->
    </ns0:fields>
</ns0:jSmaTeP-Parser-Config>
